### ISSUE TITLE
I Can't import eggs into pokemon black.

### ISSUE THREAD

**Issue by devn456** [CDNRae/pkhex-bulk-egg-generator#12]
Exception Details:
System.MissingMethodException: Method not found: 'Void PKHeX.Core.EncounterEgg..ctor(Int32, Int32, Int32, Int32, PKHeX.Core.GameVersion)'.
   at BulkImporter.BulkImporterPlugin.AddToBoxesButtonClick(Object sender, EventArgs events)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

This is my error message

**Comment by CDNRae** [comment]
Should be fixed in version 2.0.0.
