### ISSUE TITLE
Updating to a more recent PKHeX version / Providing a special PKHeX build ?

### ISSUE THREAD

**Issue by RichardPaulAstley** [CDNRae/pkhex-bulk-egg-generator#5]
Hi !
I've discovered that plugin today, and I'm really interested to work around it, especially with your Egg Generator tool because it supports older gens.
However, I'm getting a lot of issues trying to set it up because of the recents PKHeX updates.

First, the issue when you try to launch PKHeX, it's annoying but can be fixed by the user.
Then, I'm getting only errors when I try to import Pokémon to older games (Gen 2 to 6 doesn't work) : 

Exception Details:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: game
   at PKHeX.Core.GameData.Personal(GameVersion game)
   at PKHeX.Core.GameData.GetLearnset(GameVersion game, Int32 species, Int32 form)
   at PKHeX.Core.EncounterEgg.SetEncounterMoves(PKM pk, GameVersion version)
   at PKHeX.Core.EncounterEgg.ConvertToPKM(ITrainerInfo sav, EncounterCriteria criteria)
   at BulkImporter.BulkImporterPlugin.AddToBoxesButtonClick(Object sender, EventArgs events)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Is the one I'm always getting when I try to import some files to these gens. Didn't have an issue with Gen 7 / 8 but my focus would be to play on older games.

So my suggestion was : Could it be possible to have it updated for a more recent PKHeX build ? Or just to provide the PKHeX release which the plugin would work 100% fine ? PKHeX older release are getting deleted for obvious reasons, but here, it does create an issue.

Thanks a lot !

**Comment by CDNRae** [comment]
Hi there!  Sorry for the delay in getting back to you.  I'll see what I can do about ironing out those bugs and getting an updated build out shortly!

**Comment by RichardPaulAstley** [comment]
Thank you for you answer first !
No rush on that haha, I guess you have other projects that are more important for you, so it's alright if you take care of that when you have free time ! 

I'd suggest to keep the PKHeX compatible version under the hand in the future that way it'll save you some time o/ !

**Comment by CDNRae** [comment]
Should be fixed in version 2.0.0.
